"""empty message

Revision ID: 5d85a34a047b
Revises: c135305f2cde
Create Date: 2019-05-29 16:22:40.898200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d85a34a047b'
down_revision = 'c135305f2cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('image_file', sa.String(length=125), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('categories_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('image_field', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('net_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sub_cat_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['subcategories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sub_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=125), nullable=True),
    sa.Column('create_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('categories_id', sa.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint('deleted IN (0, 1)'),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
